# Generated by Django 5.1.3 on 2024-11-16 00:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.address')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2024, 11, 16, 0, 8, 39, 891640, tzinfo=datetime.timezone.utc))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.vendor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='unique_invoice_numbers_per_vendor')],
            },
        ),
    ]
