# Generated by Django 5.1.3 on 2024-11-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0004_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
