# Generated by Django 5.1.3 on 2024-11-20 13:43

import django.core.validators
from django.db import migrations, models

import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000), invoice.models.validate_real_values]),
        ),
    ]
