# Generated by Django 5.1.3 on 2024-11-20 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_date_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 20, 13, 52, 32, 415710, tzinfo=datetime.timezone.utc)),
        ),
    ]
