# Generated by Django 5.1.3 on 2024-11-22 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0010_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                  django.core.validators.MaxValueValidator(
                                                      2147483647)]),
        ),
    ]
