# Generated by Django 5.1.3 on 2024-11-22 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0011_alter_invoice_invoice_number_and_more'),
        ('invoice', '0011_vendor_tax_id'),
    ]

    operations = [
    ]
