# Generated by Django 5.1.3 on 2024-11-22 19:11

import django.db.models.deletion
from django.db import migrations, models

import invoice.models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0012_merge_20241122_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                (
                'iban', models.CharField(max_length=34, validators=[invoice.models.validate_iban])),
                ('bic', models.CharField(max_length=11, validators=[invoice.models.validate_bic])),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='invoice.bankaccount'),
        ),
    ]
