# Generated by Django 5.1.3 on 2024-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_bankaccount_vendor_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
