# Generated by Django 5.1.3 on 2024-11-24 16:04

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_address_number_address_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=34, unique=True, validators=[invoice.models.validate_iban]),
        ),
    ]
