# Generated by Django 5.1.3 on 2024-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0017_alter_address_line_2_alter_address_line_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
