# Generated by Django 5.1.3 on 2024-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0021_alter_bankaccount_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name', 'company_name'),
                                               name='unique_name_and_company_name'),
        ),
    ]
