# Generated by Django 5.1.3 on 2024-12-01 11:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_vendor_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))]),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
    ]
