# Generated by Django 5.1.3 on 2024-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0024_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3),
        ),
    ]
