# Generated by Django 5.1.3 on 2024-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0025_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('due_date'))),
                                              name='due_date_gte_date'),
        ),
    ]
