# Generated by Django 5.1.3 on 2024-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0027_remove_invoice_due_date_gte_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='due_date_gte_date',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('date'))),
                                              name='due_date_gte_date'),
        ),
    ]
