# Generated by Django 5.1.3 on 2024-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0027_remove_invoice_due_date_gte_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(
                choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'),
                         ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Austrian Dollar'),
                         ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('DKK', 'Danish Krone'),
                         ('NOK', 'Norwegian Krone'), ('HKD', 'Hong Kong Dollar')], default='EUR', max_length=3),
        ),
    ]
