# Generated by Django 5.1.3 on 2024-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0028_alter_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(
                choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'),
                         ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'),
                         ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('DKK', 'Danish Krone'),
                         ('NOK', 'Norwegian Krone'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')],
                default='EUR', max_length=3),
        ),
    ]
