# Generated by Django 5.1.3 on 2024-12-02 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0028_remove_invoice_due_date_gte_date_and_more'),
        ('invoice', '0029_alter_currency'),
    ]

    operations = [
    ]
