# Generated by Django 5.1.3 on 2024-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0030_merge_20241202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
