# Generated by Django 5.1.3 on 2024-12-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0030_merge_20241202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
