# Generated by Django 5.1.3 on 2024-12-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0030_merge_20241202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
