# Generated by Django 5.1.3 on 2024-12-06 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0031_invoice_delivery_date'),
        ('invoice', '0031_invoice_final'),
    ]

    operations = [
    ]
