# Generated by Django 5.1.3 on 2024-12-06 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0032_bankaccount_owner'),
        ('invoice', '0032_merge_0031_invoice_delivery_date_0031_invoice_final'),
    ]

    operations = [
    ]
