# Generated by Django 5.1.3 on 2024-12-06 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0033_merge_20241206_1129'),
        ('invoice', '0033_merge_20241206_1143'),
    ]

    operations = [
    ]
