# Generated by Django 5.1.3 on 2024-12-06 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0031_invoice_paid'),
        ('invoice', '0035_alter_bankaccount_bic_alter_bankaccount_iban'),
    ]

    operations = [
    ]
