# Generated by Django 5.1.4 on 2024-12-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0036_merge_20241206_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.vendor'),
            preserve_default=False,
        ),
    ]
