# Generated by Django 5.1.3 on 2024-12-08 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0031_alter_address_options_alter_bankaccount_options_and_more'),
        ('invoice', '0036_merge_20241206_1649'),
    ]

    operations = [
    ]
