# Generated by Django 5.1.4 on 2024-12-17 20:27

from django.db import migrations, models

import invoice.models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0037_merge_20241208_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bic',
            field=models.CharField(max_length=120, validators=[invoice.models.validate_bic], verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=120, validators=[invoice.models.validate_iban], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.CharField(default='', max_length=120, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='delivery date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final',
            field=models.BooleanField(default=False, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='unit'),
        ),
    ]
