# Generated by Django 5.1.4 on 2024-12-16 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0037_merge_20241208_1236'),
        ('invoice', '0039_vendor_user'),
    ]

    operations = [
    ]
