# Generated by Django 5.1.4 on 2024-12-17 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0040_merge_0037_merge_20241208_1236_0039_vendor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
