# Generated by Django 5.1.4 on 2024-12-18 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0038_alter_bankaccount_bic_alter_bankaccount_iban_and_more'),
        ('invoice', '0041_remove_customer_user_customer_vendor_and_more'),
    ]

    operations = [
    ]
