# Generated by Django 6.0 on 2025-12-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0042_merge_20241218_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='second address line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='third address line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.vendor', verbose_name='vendor'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='tax ID'),
        ),
    ]
