# Generated by Django 5.2 on 2025-04-05 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0042_merge_20241218_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='invoice_counter',
            field=models.IntegerField(default=0, verbose_name='invoice counter'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True,
                                      validators=[django.core.validators.MaxValueValidator(2147483647)],
                                      verbose_name='invoice number'),
        ),
    ]
