# Generated by Django 6.0 on 2025-12-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0043_alter_address_line_2_alter_address_line_3_and_more'),
        ('invoice', '0043_vendor_invoice_counter_alter_customer_vendor_and_more'),
    ]

    operations = [
    ]
