# Generated by Django 6.0 on 2025-12-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0044_merge_20251215_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_counter',
            field=models.IntegerField(default=0, verbose_name='invoice counter'),
        ),
    ]
