# Generated by Django 6.0 on 2025-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0045_customer_invoice_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='invoice_number_format',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='invoice number format'),
        ),
    ]
