# Generated by Django 6.0 on 2025-12-22 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0046_vendor_invoice_number_format'),
        ('invoice', '0046_vendor_invoice_number_format_and_more'),
    ]

    operations = [
    ]
