# Generated by Django 6.0 on 2025-12-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0047_merge_20251222_1847'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_numbers_per_vendor',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='invoice number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__isnull', False)),
                                               fields=('vendor', 'invoice_number'),
                                               name='unique_invoice_numbers_per_vendor'),
        ),
    ]
