# Generated by Django 6.0 on 2025-12-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0048_remove_invoice_unique_invoice_numbers_per_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=None, max_length=255, verbose_name='invoice number'),
        ),
    ]
