# Generated by Django 6.0 on 2025-12-29 01:28

import invoice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0050_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bic',
            field=models.CharField(blank=True, max_length=120, validators=[invoice.models.validate_bic], verbose_name='BIC'),
        ),
    ]
