# Generated by Django 6.0 on 2025-12-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0051_alter_bankaccount_bic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_numbers_per_vendor',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('vendor', 'invoice_number'), name='unique_invoice_numbers_per_vendor'),
        ),
    ]
