# Generated by Django 6.0 on 2026-01-18 17:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0052_remove_invoice_unique_invoice_numbers_per_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
