# Generated by Django 6.0 on 2026-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0053_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logos', verbose_name='logo path'),
        ),
    ]
